### ISSUE TITLE
Add doc on what to expose to make pypi objects persistent

### ISSUE THREAD

**Issue by jmellor** [tonyseek/docker-devpi#1]
The current implementation does not have object persistence.  Stopping or crashing the image causes loss of artifacts.

The existing Dockerfile exposes the artifact repository as an exported volume, but it is not documented what is required to use it.

So, a fix is simple, and easily added to the install part of the README.MD:
$ sudo mkdir /var/lib/devpi

Followed by a small change in how to run the docker image:
$ docker run \
        -d \
        --name=devpi \
        -p 80:80 \
        -v /var/lib/devpi:/var/lib/devpi \
        tonyseek/devpi:2.1.5-1

This should allow the artifacts to become persistent.

What do you think?

**Comment by tonyseek** [comment]
Thanks for your advice.

The README has been updated with volume options, in the latest release `4.4.0-1`.
